# This is used by rabbitmq-peer-discovery-k8s for cluster formation
#
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq
rules:
- apiGroups:
  - ""
  resources:
  - "endpoints"
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
