# This is used by rabbitmq-peer-discovery-k8s for cluster formation
#
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
