apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 2x2-pod
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: 2x2-pod
        image: kaszper/traffic-component:latest
        imagePullPolicy: Always