apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  podManagementPolicy: OrderedReady
  # We want 3 RabbitMQ nodes
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  # This service is responsible for:
  # * the network identity of the set
  # * cluster formation
  #
  # Pod hostnames are set using the following naming convention:
  #   podName.serviceName.default.svc.cluster.local
  serviceName: reliable-rabbit
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
    spec:
      storageClassName: ssd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "100Gi"
  template:
    metadata:
      annotations:
        prometheus.io/port: "15692"
        prometheus.io/scrape: "true"
      name: rabbitmq
      labels:
        app: rabbitmq
            