# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: rabbitmq-data
#   labels:
#     stage: production
#     name: rabbitmq-storage 
#     app: rabbitmq
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   storageClassName: ssd #do-block-storage



# In order to provision SSD disks for storage, we first need to define the pd-ssd type in GCP
#
# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/ssd-pd
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
