# Enable specific RabbitMQ plugins
#
# https://www.rabbitmq.com/plugins.html
#
# rabbitmq@rabbitmq-0:/$ rabbitmq-plugins list
# Listing plugins with pattern ".*" ...
#  Configured: E = explicitly enabled; e = implicitly enabled
#  | Status: * = running on rabbit@rabbitmq-0.reliable-rabbit.default
#  |/
# [  ] rabbitmq_amqp1_0                  3.8.9
# [  ] rabbitmq_auth_backend_cache       3.8.9
# [  ] rabbitmq_auth_backend_http        3.8.9
# [  ] rabbitmq_auth_backend_ldap        3.8.9
# [  ] rabbitmq_auth_backend_oauth2      3.8.9
# [  ] rabbitmq_auth_mechanism_ssl       3.8.9
# [  ] rabbitmq_consistent_hash_exchange 3.8.9
# [  ] rabbitmq_event_exchange           3.8.9
# [  ] rabbitmq_federation               3.8.9
# [  ] rabbitmq_federation_management    3.8.9
# [  ] rabbitmq_jms_topic_exchange       3.8.9
# [E*] rabbitmq_management               3.8.9
# [e*] rabbitmq_management_agent         3.8.9
# [  ] rabbitmq_mqtt                     3.8.9
# [  ] rabbitmq_peer_discovery_aws       3.8.9
# [e*] rabbitmq_peer_discovery_common    3.8.9
# [  ] rabbitmq_peer_discovery_consul    3.8.9
# [  ] rabbitmq_peer_discovery_etcd      3.8.9
# [E*] rabbitmq_peer_discovery_k8s       3.8.9
# [E*] rabbitmq_prometheus               3.8.9
# [  ] rabbitmq_random_exchange          3.8.9
# [  ] rabbitmq_recent_history_exchange  3.8.9
# [  ] rabbitmq_sharding                 3.8.9
# [  ] rabbitmq_shovel                   3.8.9
# [  ] rabbitmq_shovel_management        3.8.9
# [  ] rabbitmq_stomp                    3.8.9
# [  ] rabbitmq_top                      3.8.9
# [  ] rabbitmq_tracing                  3.8.9
# [  ] rabbitmq_trust_store              3.8.9
# [e*] rabbitmq_web_dispatch             3.8.9
# [  ] rabbitmq_web_mqtt                 3.8.9
# [  ] rabbitmq_web_mqtt_examples        3.8.9
# [  ] rabbitmq_web_stomp                3.8.9
# [  ] rabbitmq_web_stomp_examples       3.8.9
apiVersion: v1
kind: ConfigMap
metadata:
  name: enabled-plugins
data:
  value: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_prometheus].
